Added support for WITH statements for DatabaseViews
vitusortner/floor pull request #443
Opened 2020-12-09 11:36 UTC by themadmrj

2020-12-09 21:11 UTC, vitusortner requested changes

2020-12-09 21:11 UTC, vitusortner commented on floor_generator/lib/processor/view_processor.dart
> +                lowerQuery.contains('select')))) {
💡 We could think about extracting these checks into functions similar to shown in the following snippet. I realized that a `WITH` query needs **at least two** `SELECT`s. One in the `WITH` statement and another one in the statement that provides the database view.

```suggestion
    if (query == null || !(query.isSelectQuery || query.isCteWithSelect)) {
      throw _processorError.missingQuery;
    }
    return query;
  }
}

extension on String {
  bool get isSelectQuery => toLowerCase().trimLeft().startsWith('select');

  /// whether the string is a common table expression
  /// followed by a `SELECT` query
  bool get isCteWithSelect {
    final lowerCasedString = toLowerCase();
    return lowerCasedString.trimLeft().startsWith('with') &&
        'select'.allMatches(lowerCasedString).length >= 2;
  }
}
```

2020-12-09 21:11 UTC, vitusortner commented on floor_generator/test/processor/view_processor_test.dart
> +
💡 We could think about adding some tests that assert the error cases:

```suggestion
test('Throws when processing view without SELECT', () async {
    final classElement = await createClassElement('''
      @DatabaseView("DELETE all from Person")
      class Person {
        final int id;
      
        final String name;
      
        Person(this.id, this.name);
      }
    ''');

    final actual = () => ViewProcessor(classElement, {}).process();

    expect(actual, throwsInvalidGenerationSourceError());
  });

  test(
      'Throws when processing view starting with WITH statement without SELECT',
      () async {
    final classElement = await createClassElement('''
      @DatabaseView("WITH subquery")
      class Person {
        final int id;
      
        final String name;
      
        Person(this.id, this.name);
      }
    ''');

    final actual = () => ViewProcessor(classElement, {}).process();

    expect(actual, throwsInvalidGenerationSourceError());
  });

  test(
      'Throws when processing view starting with WITH statement with only one SELECT',
      () async {
    final classElement = await createClassElement('''
      @DatabaseView("WITH subquery as (SELECT * from otherentity)")
      class Person {
        final int id;
      
        final String name;
      
        Person(this.id, this.name);
      }
    ''');

    final actual = () => ViewProcessor(classElement, {}).process();

    expect(actual, throwsInvalidGenerationSourceError());
  });
```

2020-12-09 22:07 UTC, themadmrj commented on floor_generator/test/processor/view_processor_test.dart
> +    const query = 'WITH subquery as (SELECT * from otherentity) SELECT subquery.*';
I don't get why there are errors everywhere now all of a sudden. I'll take a better look tomorrow.

2020-12-10 08:15 UTC, vitusortner requested changes

2020-12-10 08:15 UTC, vitusortner commented on floor_generator/lib/processor/view_processor.dart
>        throw _processorError.missingQuery;
💡 Oops. It seems like we messed up the file a bit. We can delete this and all following lines.

2020-12-10 08:15 UTC, vitusortner commented on floor_generator/test/processor/view_processor_test.dart
> +  test('Process view starting with WITH statement', () async {
💡 It might be a good idea to run auto format another time on this file.

2020-12-10 11:23 UTC, themadmrj commented
The test was cancelled but it seems all tests passed.

2020-12-10 11:32 UTC, themadmrj reviewed
Everything seems A-OK

2020-12-10 15:26 UTC, vitusortner approved these changes
👏 thanks for your contribution!

2020-12-10 15:26 UTC, merged

2020-12-10 15:37 UTC, themadmrj commented
> 👏 thanks for your contribution!

My pleasure, an Android I'm a huge fan of Room so it's only natural that I think floor's the best database library for Flutter!